name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Vue.js Version
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
            echo "=== 开始构建 ==="
            echo "当前目录: $(pwd)"
            ls -la
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              npm run build -- --mode production
            else
              npm run build -- --mode test
            fi
            echo "=== 构建完成 ==="
            echo "dist 目录内容:"
            ls -la dist/
  
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=pagame --compatibility-date=2024-01-01